/** @generated by fresh */
import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/index.tsx";
import * as $2 from "./islands/WalletConnect.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/index.tsx": $1,
  },
  islands: {
    "./islands/WalletConnect.tsx": $2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
