// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $learning_index from "./routes/learning/index.tsx";
import * as $learning_quiz from "./routes/learning/quiz.tsx";
import * as $QuizSession from "./islands/QuizSession.tsx";
import * as $WalletConnect from "./islands/WalletConnect.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/learning/index.tsx": $learning_index,
    "./routes/learning/quiz.tsx": $learning_quiz,
  },
  islands: {
    "./islands/QuizSession.tsx": $QuizSession,
    "./islands/WalletConnect.tsx": $WalletConnect,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
